//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CriminalDBServiceReference.ICriminalDBService")]
    public interface ICriminalDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalDBService/Search", ReplyAction="http://tempuri.org/ICriminalDBService/SearchResponse")]
        CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchResponse Search(CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICriminalDBService/Search", ReplyAction="http://tempuri.org/ICriminalDBService/SearchResponse")]
        System.Threading.Tasks.Task<CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchResponse> SearchAsync(CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Search", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CriminalDB.Services.ServiceRequest request;
        
        public SearchRequest() {
        }
        
        public SearchRequest(CriminalDB.Services.ServiceRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SearchResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public SearchResponse() {
        }
        
        public SearchResponse(bool SearchResult, string errorMessage) {
            this.SearchResult = SearchResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICriminalDBServiceChannel : CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.ICriminalDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CriminalDBServiceClient : System.ServiceModel.ClientBase<CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.ICriminalDBService>, CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.ICriminalDBService {
        
        public CriminalDBServiceClient() {
        }
        
        public CriminalDBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CriminalDBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalDBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CriminalDBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchResponse CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.ICriminalDBService.Search(CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public bool Search(CriminalDB.Services.ServiceRequest request, out string errorMessage) {
            CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchRequest inValue = new CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchRequest();
            inValue.request = request;
            CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchResponse retVal = ((CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.ICriminalDBService)(this)).Search(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.SearchResult;
        }
        
        public System.Threading.Tasks.Task<CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchResponse> SearchAsync(CriminalDB.WcfService.Integration.Tests.CriminalDBServiceReference.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
    }
}
